name = "test-remix-typescript"
type = "javascript"

zone_id = ""
account_id = "f3f3d5a46efab05dec7724a7a5dd6c1b"
route = ""
workers_dev = true

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build && npm run build:worker"
watch_dir = "build/index.js"

[build.upload]
format="service-worker"
